# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(up) {transformation: [-1.9591f,0.156f,0.013f,0.0782f,0.1565f,1.9523f,0.1629f,3.0783f,0f,0.1634f,-1.9585f,3.3721f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-1.2437f,0.099f,0.0083f,0.088f,0.0994f,1.2394f,0.1034f,3.2015f,0f,0.1038f,-1.2434f,3.7418f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_hand) {transformation: [-1f,0f,0f,-2.0425f,0f,0.9791f,0.2036f,-0.1307f,0f,0.2036f,-0.9791f,3.9225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-2.0714f,0f,0f,-2.0425f,0f,2.0681f,-0.1176f,1.2286f,0f,-0.1176f,-2.0681f,2.5593f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.5321f,0f,0f,-1.8786f,0f,1.5244f,-0.1533f,2.8625f,0f,-0.1533f,-1.5244f,2.1783f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_hand) {transformation: [-1f,0f,0f,2.1336f,0f,0.9916f,0.1296f,-0.6536f,0f,0.1296f,-0.9916f,0.3314f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-2.0714f,0f,0f,2.1336f,0f,1.4225f,1.5058f,1.3729f,0f,1.5058f,-1.4225f,0.6668f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.5321f,0f,0f,1.9697f,0f,1.1616f,0.9991f,2.4776f,0f,0.9991f,-1.1616f,1.5816f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-2.8396f,0.2269f,0f,0f,0.2269f,2.8396f,0f,2.0998f,0f,0f,-2.8487f,-0.7825f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_foot) {transformation: [-1f,0f,0f,1.1f,0f,0.9143f,-0.405f,1.3343f,0f,-0.405f,-0.9143f,-2.8463f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_knee) {transformation: [-1.2617f,0f,0f,1.1182f,0f,1.2209f,0.3183f,0.5683f,0f,0.3183f,-1.2209f,-1.2256f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-2.0278f,0f,0f,1.0815f,0f,1.9333f,-0.6118f,2.7043f,0f,-0.6118f,-1.9333f,-2.0309f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_foot) {transformation: [-1f,0f,0f,-1.1f,0f,0.9748f,-0.2232f,0.2677f,0f,-0.2232f,-0.9748f,-3.5028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_knee) {transformation: [-1.2617f,0f,0f,-1.1182f,0f,1.233f,-0.2676f,0.3165f,0f,-0.2676f,-1.233f,-1.7109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-2.0278f,0f,0f,-1.0815f,0f,2.0266f,-0.0692f,2.7193f,0f,-0.0692f,-2.0266f,-2.0671f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(group) {transformation: [-1.9904f,0f,0f,0f,0f,1.9904f,0f,2.3783f,0f,0f,-1.9904f,0.4285f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}