# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(up) {transformation: [-1.9579f,0.17f,0.0209f,0.0847f,0.1713f,1.9433f,0.2386f,2.941f,0f,0.2395f,-1.9507f,3.3701f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-1.2429f,0.1079f,0.0133f,0.0942f,0.1087f,1.2337f,0.1515f,3.0497f,0f,0.1521f,-1.2384f,3.7444f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_hand) {transformation: [-1f,0f,0f,-2.0439f,0f,1f,0f,-0.5939f,0f,0f,-1f,3.8309f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-2.0714f,0f,0f,-2.0439f,0f,2.04f,0.3597f,1.1158f,0f,0.3597f,-2.04f,2.8631f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.5321f,0f,0f,-1.88f,0f,1.4799f,-0.3965f,2.6669f,0f,-0.3965f,-1.4799f,2.2145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_hand) {transformation: [-1f,0f,0f,2.1468f,0f,0.9763f,0.2164f,-0.6371f,0f,0.2164f,-0.9763f,0.1544f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-2.0714f,0f,0f,2.1468f,0f,1.3994f,1.5272f,1.3823f,0f,1.5272f,-1.3994f,0.508f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.5321f,0f,0f,1.9829f,0f,1.0834f,1.0834f,2.4544f,0f,1.0834f,-1.0834f,1.527f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-2.8378f,0.2483f,0f,0f,0.2483f,2.8378f,0f,1.9727f,0f,0f,-2.8487f,-0.7825f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_foot) {transformation: [-1f,0f,0f,1.1f,0f,0.8576f,-0.5143f,1.0728f,0f,-0.5143f,-0.8576f,-2.5417f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_knee) {transformation: [-1.2617f,0f,0f,1.1182f,0f,1.2528f,0.1497f,0.5337f,0f,0.1497f,-1.2528f,-0.8321f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-2.0278f,0f,0f,1.0815f,0f,1.8286f,-0.8766f,2.5587f,0f,-0.8766f,-1.8286f,-1.9481f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_foot) {transformation: [-1f,0f,0f,-1.1f,0f,0.9965f,-0.0837f,0.0121f,0f,-0.0837f,-0.9965f,-3.9871f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_knee) {transformation: [-1.2617f,0f,0f,-1.1182f,0f,1.2413f,-0.2264f,0.0012f,0f,-0.2264f,-1.2413f,-2.1946f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-2.0278f,0f,0f,-1.0815f,0f,2.0089f,0.2761f,2.4314f,0f,0.2761f,-2.0089f,-2.1577f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(group) {transformation: [-1.9904f,0f,0f,0f,0f,1.9904f,0f,2.2512f,0f,0f,-1.9904f,0.4285f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] at @s run function animated_java:cart/animations/walk/zzz/frames/15_root_function