# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(up) {transformation: [-1.9604f,-0.1366f,-0.0237f,-0.0677f,-0.1386f,1.9315f,0.3355f,3.1139f,0f,0.3363f,-1.9363f,3.367f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-1.2446f,-0.0867f,-0.0151f,-0.0741f,-0.088f,1.2262f,0.213f,3.204f,0f,0.2135f,-1.2293f,3.7463f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_hand) {transformation: [-1f,0f,0f,-2.14f,0f,0.8946f,0.4468f,-0.2668f,0f,0.4468f,-0.8946f,1.2472f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-2.0714f,0f,0f,-2.14f,0f,1.9455f,0.7112f,1.5829f,0f,0.7112f,-1.9455f,0.5406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.5321f,0f,0f,-1.9761f,0f,1.0725f,1.0941f,2.6928f,0f,1.0941f,-1.0725f,1.5779f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_hand) {transformation: [-1f,0f,0f,2.0652f,0f,0.9983f,-0.0586f,-0.6835f,0f,-0.0586f,-0.9983f,3.306f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-2.0714f,0f,0f,2.0652f,0f,2.002f,0.5317f,1.1374f,0f,0.5317f,-2.002f,2.5066f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.5321f,0f,0f,1.9014f,0f,1.5184f,-0.2043f,2.677f,0f,-0.2043f,-1.5184f,2.1117f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-2.8416f,-0.2009f,0f,0f,-0.2009f,2.8416f,0f,2.1564f,0f,0f,-2.8487f,-0.7825f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_foot) {transformation: [-1f,0f,0f,1.1f,0f,0.9937f,0.1118f,0.1491f,0f,0.1118f,-0.9937f,-4.6529f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_knee) {transformation: [-1.2617f,0f,0f,1.1182f,0f,1.248f,-0.1858f,0.0797f,0f,-0.1858f,-1.248f,-2.8617f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-2.0278f,0f,0f,1.0815f,0f,1.8874f,0.7416f,2.4464f,0f,0.7416f,-1.8874f,-2.282f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_foot) {transformation: [-1f,0f,0f,-1.1f,0f,0.7576f,-0.6527f,0.7996f,0f,-0.6527f,-0.7576f,-2.0924f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_knee) {transformation: [-1.2617f,0f,0f,-1.1182f,0f,1.2492f,-0.1773f,0.718f,0f,-0.1773f,-1.2492f,-0.3017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-2.0278f,0f,0f,-1.0815f,0f,1.6309f,-1.2051f,2.5275f,0f,-1.2051f,-1.6309f,-1.8363f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(group) {transformation: [-1.9904f,0f,0f,0f,0f,1.9904f,0f,2.4348f,0f,0f,-1.9904f,0.4285f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}