# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on vehicle on passengers if entity @s[type=player] run function snc:shifters/mobs/female/head {rotate:0,"frame":3}
execute on vehicle on passengers if entity @s[tag=transform] run rotate @s ~ -11.25
execute on vehicle on passengers if entity @s[type=player] run function snc:shifters/mobs/regeneration with storage minecraft:female
execute on vehicle run attribute @s minecraft:scale base set 3.3