# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove animated_java.cart.animation.idle.playing
tag @s remove animated_java.cart.animation.jump_start.playing
tag @s remove animated_java.cart.animation.jump_mid.playing
tag @s remove animated_java.cart.animation.jump_end.playing