# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(neck) {transformation: [-0.8961f,0f,0f,0f,0f,0.1291f,0.8867f,6.7633f,0f,0.8867f,-0.1291f,-0.7104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_thumb_2) {transformation: [-0.3445f,-0.6511f,-0.5102f,-0.1239f,0.2169f,0.4622f,-0.7364f,4.6871f,0.7983f,-0.4066f,-0.0201f,-0.1735f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_thumb) {transformation: [-0.3445f,-0.8272f,-0.0083f,-0.441f,0.2169f,-0.0816f,-0.8656f,4.7053f,0.7983f,-0.3348f,0.2316f,-0.1661f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_fingers2) {transformation: [0.4445f,-0.5874f,-0.5102f,0.0714f,-0.3272f,0.3919f,-0.7364f,4.2539f,0.7059f,0.5516f,-0.0201f,0.1461f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_fingers) {transformation: [-0.0371f,-0.7357f,-0.5102f,-0.1431f,0.0012f,0.5106f,-0.7364f,4.394f,0.8953f,-0.0312f,-0.0201f,0.1623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(scout) {transformation: [0f,0f,0f,-0.1656f,0f,0f,0f,4.2978f,0f,0f,0f,0.0004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_hand) {transformation: [-0.3445f,-0.6511f,-0.5102f,-0.5638f,0.2169f,0.4622f,-0.7364f,4.6443f,0.7983f,-0.4066f,-0.0201f,-0.0923f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.3035f,-0.4625f,1.1033f,-1.2075f,-1.1705f,0.3501f,-0.1752f,5.2139f,-0.2473f,-1.0894f,-0.5247f,-1.7418f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_shoulder) {transformation: [-1.2582f,0.0327f,-0.3768f,-0.9019f,-0.1689f,1.1225f,0.6615f,6.5952f,0.3384f,0.682f,-1.0708f,-0.9441f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.8961f,0f,0f,-0.3966f,0f,0.5455f,0.7109f,6.7593f,0f,0.7109f,-0.5455f,-0.7428f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_thumb_2) {transformation: [-0.413f,0.4952f,0.6222f,0.5106f,-0.3936f,0.482f,-0.6448f,5.2286f,-0.691f,-0.5704f,-0.0046f,-0.1119f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_thumb) {transformation: [-0.413f,0.7806f,-0.152f,0.8251f,-0.3936f,-0.3494f,-0.7252f,5.1848f,-0.691f,-0.2675f,0.5039f,-0.1026f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_fingers2) {transformation: [0.705f,0.3424f,0.4344f,0.3585f,0.0048f,0.6999f,-0.5595f,4.7444f,-0.5531f,0.4425f,0.5488f,0.1952f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_fingers) {transformation: [0.4942f,0.6083f,0.4344f,0.5211f,-0.2915f,0.6364f,-0.5595f,4.9299f,-0.6883f,0.1673f,0.5488f,0.2663f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_hand) {transformation: [-0.1969f,0.6446f,0.5905f,0.9421f,-0.4706f,0.4319f,-0.6284f,5.165f,-0.7367f,-0.4482f,0.2436f,-0.0019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.9188f,0.6333f,-0.5272f,1.8385f,0.7033f,0.1912f,-0.9961f,5.4459f,-0.4295f,-1.0419f,-0.5032f,-1.6072f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_shoulder) {transformation: [-1.1654f,-0.5701f,0.2075f,0.9019f,-0.3693f,1.0232f,0.7368f,6.5952f,-0.4813f,0.5953f,-1.0678f,-0.9441f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.8961f,0f,0f,0.3966f,0f,0.5455f,0.7109f,6.7593f,0f,0.7109f,-0.5455f,-0.7428f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-1.1457f,0f,0f,0f,0f,0.6974f,0.9089f,5.7987f,0f,0.9089f,-0.6974f,-2.0455f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_cheek) {transformation: [-0.8928f,-0.034f,0.0687f,0.4266f,-0.0394f,0.8925f,-0.0698f,5.3221f,-0.0658f,-0.0726f,-0.8907f,-2.8505f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_foot) {transformation: [-0.9161f,0f,0f,0.6177f,0f,0.9161f,0f,2.027f,0f,0f,-0.9161f,-2.4984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_knee) {transformation: [-2.7256f,0f,0f,0.6959f,0f,2.1624f,1.6593f,4.821f,0f,1.6593f,-2.1624f,-0.495f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.5394f,0f,0f,0.6319f,0f,-0.1342f,-1.5336f,4.3456f,0f,-1.5336f,0.1342f,-2.5918f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_cheek) {transformation: [-0.8805f,0.0934f,0.138f,-0.3398f,0.1057f,0.8867f,0.0743f,5.3315f,-0.1288f,0.0893f,-0.8823f,-2.8591f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_foot) {transformation: [-0.8737f,-0.1862f,0.2031f,0.105f,0f,0.6754f,0.6189f,2.4911f,-0.2755f,0.5903f,-0.6442f,-4.844f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_knee) {transformation: [-2.5995f,-0.8166f,-0.0715f,-1.1027f,-0.0001f,-0.2376f,2.7153f,2.2733f,-0.8197f,2.5896f,0.2266f,-1.2742f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.4682f,0.2655f,0.3793f,-0.6274f,0f,1.2611f,-0.8829f,4.3195f,-0.463f,-0.8421f,-1.2027f,-2.5688f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(weist) {transformation: [-1.4537f,0f,0f,0f,0f,1.4042f,0.3763f,5.7944f,0f,0.3763f,-1.4042f,-2.284f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"consume":{"px":-0.0260424284,"py":4.2424135439,"pz":0.0257022506,"ry":272.259356262,"rx":-55.2663128806}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args