# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(neck) {transformation: [-0.9292f,0f,0f,0f,0f,0.2885f,0.8832f,6.6258f,0f,0.8832f,-0.2885f,-0.7124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_thumb_2) {transformation: [-0.3573f,-0.6752f,-0.529f,-0.1285f,0.2249f,0.4793f,-0.7636f,4.473f,0.8277f,-0.4216f,-0.0209f,-0.1556f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_thumb) {transformation: [-0.3573f,-0.8577f,-0.0087f,-0.4573f,0.2249f,-0.0846f,-0.8976f,4.4918f,0.8277f,-0.3472f,0.2401f,-0.148f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_fingers2) {transformation: [0.4609f,-0.6091f,-0.529f,0.074f,-0.3393f,0.4064f,-0.7636f,4.0237f,0.7319f,0.572f,-0.0209f,0.1757f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_fingers) {transformation: [-0.0384f,-0.7629f,-0.529f,-0.1483f,0.0013f,0.5294f,-0.7636f,4.169f,0.9284f,-0.0323f,-0.0209f,0.1925f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(scout) {transformation: [0f,0f,0f,-0.1717f,0f,0f,0f,4.0692f,0f,0f,0f,0.0247f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_hand) {transformation: [-0.3573f,-0.6752f,-0.529f,-0.5846f,0.2249f,0.4793f,-0.7636f,4.4285f,0.8277f,-0.4216f,-0.0209f,-0.0715f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.3147f,-0.4795f,1.1441f,-1.2521f,-1.2137f,0.3631f,-0.1817f,5.0191f,-0.2565f,-1.1296f,-0.5441f,-1.7818f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_shoulder) {transformation: [-1.3047f,0.0339f,-0.3907f,-0.9352f,-0.1752f,1.164f,0.6859f,6.4515f,0.3509f,0.7071f,-1.1103f,-0.9547f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9292f,0f,0f,-0.4112f,0f,0.5656f,0.7372f,6.6216f,0f,0.7372f,-0.5656f,-0.7459f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_thumb_2) {transformation: [-0.4282f,0.5135f,0.6452f,0.5294f,-0.4081f,0.4997f,-0.6686f,5.0344f,-0.7165f,-0.5915f,-0.0047f,-0.0918f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_thumb) {transformation: [-0.4282f,0.8094f,-0.1576f,0.8555f,-0.4081f,-0.3623f,-0.752f,4.989f,-0.7165f,-0.2773f,0.5225f,-0.0822f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_fingers2) {transformation: [0.731f,0.3551f,0.4505f,0.3717f,0.005f,0.7258f,-0.5801f,4.5324f,-0.5735f,0.4588f,0.5691f,0.2267f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_fingers) {transformation: [0.5125f,0.6307f,0.4505f,0.5403f,-0.3022f,0.6599f,-0.5801f,4.7247f,-0.7137f,0.1734f,0.5691f,0.3004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_hand) {transformation: [-0.2041f,0.6684f,0.6123f,0.9769f,-0.488f,0.4479f,-0.6516f,4.9685f,-0.7639f,-0.4647f,0.2527f,0.0223f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.9528f,0.6567f,-0.5467f,1.9064f,0.7293f,0.1982f,-1.0328f,5.2598f,-0.4453f,-1.0804f,-0.5218f,-1.6422f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_shoulder) {transformation: [-1.2084f,-0.5911f,0.2152f,0.9352f,-0.383f,1.061f,0.7641f,6.4515f,-0.4991f,0.6172f,-1.1072f,-0.9547f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9292f,0f,0f,0.4112f,0f,0.5656f,0.7372f,6.6216f,0f,0.7372f,-0.5656f,-0.7459f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-1.188f,0f,0f,0f,0f,0.7232f,0.9425f,5.6256f,0f,0.9425f,-0.7232f,-2.0968f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_cheek) {transformation: [-0.9255f,-0.0411f,0.0713f,0.4425f,-0.0468f,0.925f,-0.0741f,5.1308f,-0.0677f,-0.0774f,-0.9234f,-2.9325f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_foot) {transformation: [-0.9499f,0f,0f,0.6405f,0f,0.9499f,0f,1.7146f,0f,0f,-0.9499f,-2.5664f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_knee) {transformation: [-2.8263f,0f,0f,0.7216f,0f,2.2422f,1.7205f,4.6118f,0f,1.7205f,-2.2422f,-0.489f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.5963f,0f,0f,0.6552f,0f,-0.1391f,-1.5902f,4.1188f,0f,-1.5902f,0.1391f,-2.6632f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_cheek) {transformation: [-0.9128f,0.0975f,0.1435f,-0.3521f,0.1102f,0.9194f,0.0768f,5.1415f,-0.1339f,0.0924f,-0.9148f,-2.9408f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_foot) {transformation: [-0.906f,-0.193f,0.2106f,0.1088f,0f,0.7004f,0.6418f,2.1874f,-0.2857f,0.6121f,-0.6679f,-5.0002f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_knee) {transformation: [-2.6954f,-0.8468f,-0.0742f,-1.1436f,-0.0001f,-0.2464f,2.8155f,1.9615f,-0.85f,2.6852f,0.235f,-1.2987f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.5224f,0.2753f,0.3933f,-0.6507f,0f,1.3076f,-0.9155f,4.0832f,-0.4801f,-0.8732f,-1.2471f,-2.641f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(weist) {transformation: [-1.5074f,0f,0f,0f,0f,1.4561f,0.3901f,5.6212f,0f,0.3901f,-1.4561f,-2.3441f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"consume":{"px":-0.0269949154,"py":4.0118198177,"pz":0.0509249361,"ry":272.2590566372,"rx":-55.2659478634}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args