# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function snc:shifters/mobs/female/action/ghost/kick/walk/damage with storage minecraft:female