# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on vehicle run attribute @s minecraft:scale base set 3.5
execute on vehicle at @s rotated ~180 0 run function snc:logic/motion/generic {"score":"female_vars","strength":0.005, "unstoppable":"false"}