# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(neck) {transformation: [-0.9144f,-0.172f,0.3664f,0.2682f,0.1061f,0.7717f,0.6271f,6.3906f,-0.3906f,0.6123f,-0.6874f,-0.2631f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_thumb_2) {transformation: [-0.4229f,0.1894f,-0.8862f,-0.9896f,0.901f,-0.0165f,-0.4335f,6.8124f,-0.0968f,-0.9818f,-0.1637f,0.3394f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_thumb) {transformation: [-0.4229f,-0.6727f,-0.6071f,-1.2602f,0.901f,-0.3837f,-0.2024f,6.8254f,-0.0968f,-0.6326f,0.7684f,0.1107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_fingers2) {transformation: [0.6341f,0.3986f,-0.6626f,-1.0454f,-0.7653f,0.2007f,-0.6116f,6.8664f,-0.1108f,0.8949f,0.4323f,0.6843f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_fingers) {transformation: [0.1895f,-0.7246f,-0.6626f,-1.2514f,0.4215f,0.6695f,-0.6116f,7.0646f,0.8868f,-0.1634f,0.4323f,0.6659f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(scout) {transformation: [0f,0f,0f,-1.2083f,0f,0f,0f,6.8584f,0f,0f,0f,0.6869f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_hand) {transformation: [-0.7053f,-0.2519f,-0.6626f,-1.4319f,0.7037f,-0.3616f,-0.6116f,6.812f,-0.0855f,-0.8977f,0.4323f,0.1341f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_forearm) {transformation: [-0.7825f,-0.2912f,-1.0954f,-1.8778f,1.0553f,-0.6729f,-0.575f,5.7338f,-0.4136f,-1.166f,0.6054f,-1.5826f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_shoulder) {transformation: [-0.4558f,1.3199f,0.4471f,-0.191f,1.1479f,0.6223f,-0.667f,6.2826f,-0.7902f,0.1427f,-1.2268f,-1.2098f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.4821f,-0.22f,0.848f,0.0243f,0.2025f,0.9137f,0.3522f,6.4361f,-0.8524f,0.3416f,-0.396f,-0.6335f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_thumb_2) {transformation: [0.7449f,-0.4203f,0.5182f,0.3033f,-0.609f,-0.111f,0.7853f,5.6878f,-0.2725f,-0.9006f,-0.3386f,4.5173f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_thumb) {transformation: [0.7449f,0.2387f,0.6231f,0.2608f,-0.609f,0.6246f,0.4888f,5.9721f,-0.2725f,-0.7436f,0.6106f,4.3099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_fingers2) {transformation: [-0.4939f,0.0902f,0.8648f,0.4057f,0.77f,-0.4165f,0.4832f,5.7264f,0.4038f,0.9046f,0.1363f,4.8534f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_fingers) {transformation: [0.0625f,-0.4982f,0.8648f,0.2683f,0.1657f,0.8597f,0.4832f,5.9702f,-0.9842f,0.1131f,0.1363f,4.9144f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_hand) {transformation: [0.5017f,0.0189f,0.8648f,0.3206f,-0.8419f,0.24f,0.4832f,6.1348f,-0.1984f,-0.9706f,0.1363f,4.3233f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_forearm) {transformation: [-0.927f,0.2224f,0.9942f,0.6532f,-0.9902f,0.1194f,-0.95f,6.2388f,-0.2396f,-1.354f,0.0795f,2.2771f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_shoulder) {transformation: [0.3506f,0.0832f,1.4213f,0.7795f,-1.4218f,-0.0541f,0.354f,5.8749f,0.0725f,-1.4629f,0.0677f,0.506f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.4821f,-0.22f,0.848f,0.4511f,0.2025f,0.9137f,0.3522f,6.2568f,-0.8524f,0.3416f,-0.396f,0.1209f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(chest) {transformation: [-0.6164f,-0.2813f,1.0842f,0.6644f,0.2589f,1.1683f,0.4503f,4.7084f,-1.0898f,0.4367f,-0.5063f,-0.8869f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_cheek) {transformation: [-0.8455f,0.0091f,0.5339f,1.3009f,0.054f,0.9962f,0.0686f,3.732f,-0.5313f,0.0869f,-0.8427f,-1.0011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_foot) {transformation: [-1.0209f,-0.0258f,0.0493f,1.0942f,-0.0244f,1.0217f,0.0295f,-3.2194f,-0.0501f,0.0283f,-1.0208f,1.2825f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_knee) {transformation: [-3.0386f,-0.063f,0.1228f,1.0993f,-0.0485f,3.0213f,0.3487f,0.9777f,-0.1292f,0.3464f,-3.0192f,1.6421f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1.7169f,0.0572f,-0.0212f,1.1201f,0.0517f,1.0469f,-1.3612f,2.6969f,-0.0324f,-1.361f,-1.0479f,-0.5088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_cheek) {transformation: [-0.6493f,0.1422f,0.7471f,0.667f,0.2714f,0.961f,0.0529f,3.8237f,-0.7104f,0.2371f,-0.6626f,-1.5252f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_foot) {transformation: [-0.1937f,-0.0962f,0.9992f,-0.3574f,0.3791f,0.9353f,0.1635f,-3.0023f,-0.9295f,0.4015f,-0.1416f,-4.5136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_knee) {transformation: [-0.9171f,-0.6953f,2.8156f,-1.2309f,1.3468f,2.5132f,1.0593f,0.558f,-2.5685f,1.566f,-0.4498f,-2.4383f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.4946f,0.8366f,1.4166f,0.0885f,0.8655f,1.3903f,-0.519f,2.7646f,-1.3992f,0.5642f,-0.8218f,-1.452f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(weist) {transformation: [-1.1959f,-0.019f,1.0961f,0.6644f,0.0785f,1.6165f,0.1137f,4.3837f,-1.0934f,0.1368f,-1.1907f,-0.9275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"locators":{"consume":{"px":-1.1079380847,"py":6.9040963749,"pz":0.8161810625,"ry":236.8777991791,"rx":-37.7043781873}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args